model_name_or_path: ./checkpoints/pretrained/JarvisArt-preview/
template: qwen2_vl
infer_backend: huggingface  # choices: [huggingface, vllm]
trust_remote_code: true
# infer_backend: vllm
vllm_enforce_eager: true
max_new_tokens: 10240
vllm_maxlen: 10240
